# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/rom_blk/rom_blk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_blk || ORIG_REF_NAME==rom_blk}]

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM}]

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]
