# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files c:/Users/kowalsif/Desktop/neural/neural_network/Neural_Network.srcs/sources_1/imports/Verilog/rom.coe
add_files c:/Users/kowalsif/Desktop/neural/neural_network/Verilog/weights.coe

read_ip c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/rom_blk/rom_blk.xci
set_property used_in_implementation false [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/rom_blk/rom_blk.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/rom_blk/rom_blk.xci]

read_ip c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/RAM/RAM.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/RAM/RAM.xci]

read_ip c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_verilog {
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Divisor_non_restoring.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Denominator.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/DelayLoop.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Weight_Reg_Bank.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Shifter.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Multi_Sum_PY.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/LayerMux.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Elliot_Activation.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/DebouncerWithoutLatch.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/ClockedOneShot.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/ROM_Controller.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/RAM_Read_Driver.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/ram_access.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/RAMMux.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Neural_Unit.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Network_Controller.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/MassAnd_py.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Data_Reg_Bank.v
  C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.srcs/sources_1/imports/Verilog/Network.v
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kowalsif/Desktop/neural/neural_network/project_1/project_1.data/wt [current_project]
set_property parent.project_dir C:/Users/kowalsif/Desktop/neural/neural_network/project_1 [current_project]
synth_design -top Network -part xc7z010clg400-1
write_checkpoint Network.dcp
report_utilization -file Network_utilization_synth.rpt -pb Network_utilization_synth.pb
