# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
set_property used_in_implementation false [get_files -all c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fendrirj/Vivado/network/Neural_Network.cache/wt [current_project]
set_property parent.project_dir C:/Users/fendrirj/Vivado/network [current_project]
synth_design -top blk_mem_gen_1 -part xc7z010clg400-1 -mode out_of_context

rename_ref -prefix_all blk_mem_gen_1
write_checkpoint -noxdef blk_mem_gen_1.dcp
report_utilization -file blk_mem_gen_1_utilization_synth.rpt -pb blk_mem_gen_1_utilization_synth.pb
if { [catch {
  file copy -force C:/Users/fendrirj/Vivado/network/Neural_Network.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
  write_verilog -force -mode synth_stub c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_stub.v
  write_vhdl -force -mode synth_stub c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_stub.vhdl
  write_verilog -force -mode funcsim c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_funcsim.v
  write_vhdl -force -mode funcsim c:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_funcsim.vhdl
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy supporting IP files."
}
