# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/rom.coe
add_files C:/Users/fendrirj/Vivado/network/Verilog/weights.coe
add_files C:/Users/fendrirj/Git_Repos/neural_network/Verilog/Neural_ROM.coe
add_files C:/Users/fendrirj/Git_Repos/neural_network/Verilog/weights.coe
add_files -quiet C:/Users/fendrirj/Vivado/network/Neural_Network.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/fendrirj/Vivado/network/Neural_Network.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/fendrirj/Vivado/network/Neural_Network.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/fendrirj/Vivado/network/Neural_Network.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet C:/Users/fendrirj/Vivado/network/Neural_Network.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files C:/Users/fendrirj/Vivado/network/Neural_Network.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Divisor_non_restoring.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Denominator.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/DelayLoop.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Weight_Reg_Bank.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Shifter.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Multi_Sum_PY.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/LayerMux.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Elliot_Activation.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/DebouncerWithoutLatch.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/ClockedOneShot.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/ROM_Controller.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/RAM_Read_Driver.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/ram_access.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/RAMMux_py.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Neural_Unit.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Network_Controller.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/MassAnd_py.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/imports/Verilog/Data_Reg_Bank.v
  C:/Users/fendrirj/Vivado/network/Neural_Network.srcs/sources_1/new/Network.v
}
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fendrirj/Vivado/network/Neural_Network.cache/wt [current_project]
set_property parent.project_dir C:/Users/fendrirj/Vivado/network [current_project]
synth_design -top Network -part xc7z010clg400-1 -fsm_extraction off
write_checkpoint Network.dcp
report_utilization -file Network_utilization_synth.rpt -pb Network_utilization_synth.pb
